apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
spec:
  capacity:
    storage: 10Gi
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/reddisekhara_n"
