kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heketi-service-account
subjects:
- kind: ServiceAccount
  name: heketi-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: heketi-service-account
  apiGroup: rbac.authorization.k8s.io
